var _a, _b, _c, _d, _e, _f, _g, _h, _j, _k, _l, _m, _o, _p, _q;
import { ChainId, ChainKey, CoinKey } from './base.types';
export var defaultCoins = [
    // NATIVE COINS
    // > ETH
    {
        key: CoinKey.ETH,
        name: CoinKey.ETH,
        logoURI: 'https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2/logo.png',
        verified: true,
        chains: (_a = {},
            _a[ChainKey.ETH] = {
                id: '0x0000000000000000000000000000000000000000',
                symbol: CoinKey.ETH,
                decimals: 18,
                chainId: ChainId.ETH,
                chainKey: ChainKey.ETH,
                key: CoinKey.ETH,
                name: CoinKey.ETH,
                logoURI: 'https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2/logo.png',
            },
            _a[ChainKey.BSC] = {
                id: '0x2170ed0880ac9a755fd29b2688956bd959f933f8',
                symbol: CoinKey.ETH,
                decimals: 18,
                chainId: ChainId.BSC,
                chainKey: ChainKey.BSC,
                key: CoinKey.ETH,
                name: CoinKey.ETH,
                logoURI: 'https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2/logo.png',
            },
            _a[ChainKey.POL] = {
                id: '0xfd8ee443ab7be5b1522a1c020c097cff1ddc1209',
                symbol: CoinKey.ETH,
                decimals: 18,
                chainId: ChainId.POL,
                chainKey: ChainKey.POL,
                key: CoinKey.ETH,
                name: CoinKey.ETH,
                logoURI: 'https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2/logo.png',
            },
            _a[ChainKey.DAI] = {
                id: '0xa5c7cb68cd81640d40c85b2e5ec9e4bb55be0214',
                symbol: CoinKey.ETH,
                decimals: 18,
                chainId: ChainId.DAI,
                chainKey: ChainKey.DAI,
                key: CoinKey.ETH,
                name: CoinKey.ETH,
                logoURI: 'https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2/logo.png',
            },
            _a[ChainKey.OPT] = {
                // guessed from debank api
                id: '0x4200000000000000000000000000000000000006',
                symbol: CoinKey.ETH,
                decimals: 18,
                chainId: ChainId.OPT,
                chainKey: ChainKey.OPT,
                key: CoinKey.ETH,
                name: CoinKey.ETH,
                logoURI: 'https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2/logo.png',
            },
            _a[ChainKey.OKT] = {
                // guessed from debank api
                id: '0xef71ca2ee68f45b9ad6f72fbdb33d707b872315c',
                symbol: CoinKey.ETH,
                decimals: 18,
                chainId: ChainId.OKT,
                chainKey: ChainKey.OKT,
                key: CoinKey.ETH,
                name: CoinKey.ETH,
                logoURI: 'https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2/logo.png',
            },
            // [ChainKey.ARB]: { // WETH
            //   id: '0x82af49447d8a07e3bd95bd0d56f35241523fbab1',
            //   symbol: CoinKey.ETH,
            //   decimals: 18,
            //   chainId: ChainId.ARB,
            //   chainKey: ChainKey.ARB,
            //   key: CoinKey.ETH,
            //   name: CoinKey.ETH,
            //   logoURI: 'https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2/logo.png',
            // },
            _a[ChainKey.ONE] = {
                id: '0x6983d1e6def3690c4d616b13597a09e6193ea013',
                symbol: CoinKey.ETH,
                decimals: 18,
                chainId: ChainId.ONE,
                chainKey: ChainKey.ONE,
                key: CoinKey.ETH,
                name: CoinKey.ETH,
                logoURI: 'https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2/logo.png',
            },
            // Testnets
            _a[ChainKey.ROP] = {
                id: '0x0000000000000000000000000000000000000000',
                symbol: CoinKey.ETH,
                decimals: 18,
                chainId: ChainId.ROP,
                chainKey: ChainKey.ROP,
                key: CoinKey.ETH,
                name: CoinKey.ETH,
                logoURI: 'https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2/logo.png',
            },
            _a[ChainKey.RIN] = {
                id: '0x0000000000000000000000000000000000000000',
                symbol: CoinKey.ETH,
                decimals: 18,
                chainId: ChainId.RIN,
                chainKey: ChainKey.RIN,
                key: CoinKey.ETH,
                name: CoinKey.ETH,
                logoURI: 'https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2/logo.png',
            },
            _a[ChainKey.GOR] = {
                id: '0x0000000000000000000000000000000000000000',
                symbol: CoinKey.ETH,
                decimals: 18,
                chainId: ChainId.GOR,
                chainKey: ChainKey.GOR,
                key: CoinKey.ETH,
                name: CoinKey.ETH,
                logoURI: 'https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2/logo.png',
            },
            _a[ChainKey.KOV] = {
                id: '0x0000000000000000000000000000000000000000',
                symbol: CoinKey.ETH,
                decimals: 18,
                chainId: ChainId.KOV,
                chainKey: ChainKey.KOV,
                key: CoinKey.ETH,
                name: CoinKey.ETH,
                logoURI: 'https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2/logo.png',
            },
            _a[ChainKey.ONET] = {
                id: '0x268d6ff391b41b36a13b1693bd25f87fb4e4b392',
                symbol: CoinKey.ETH,
                decimals: 18,
                chainId: ChainId.ONET,
                chainKey: ChainKey.ONET,
                key: CoinKey.ETH,
                name: CoinKey.ETH,
                logoURI: 'https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2/logo.png',
            },
            _a[ChainKey.BSCT] = {
                id: '0xd66c6b4f0be8ce5b39d52e0fd1344c389929b378',
                symbol: CoinKey.ETH,
                decimals: 18,
                chainId: ChainId.BSCT,
                chainKey: ChainKey.BSCT,
                key: CoinKey.ETH,
                name: CoinKey.ETH,
                logoURI: 'https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2/logo.png',
            },
            _a),
    },
    // > MATIC
    {
        key: CoinKey.MATIC,
        name: CoinKey.MATIC,
        logoURI: 'https://etherscan.io/token/images/matictoken_28.png',
        verified: true,
        chains: (_b = {},
            _b[ChainKey.ETH] = {
                id: '0x7d1afa7b718fb893db30a3abc0cfc608aacfebb0',
                symbol: CoinKey.MATIC,
                decimals: 18,
                chainId: ChainId.ETH,
                chainKey: ChainKey.ETH,
                key: CoinKey.MATIC,
                name: CoinKey.MATIC,
                logoURI: 'https://etherscan.io/token/images/matictoken_28.png',
            },
            _b[ChainKey.BSC] = {
                id: '0xa90cb47c72f2c7e4411e781772735d9317d08dd4',
                symbol: CoinKey.MATIC,
                decimals: 8,
                chainId: ChainId.BSC,
                chainKey: ChainKey.BSC,
                key: CoinKey.MATIC,
                name: CoinKey.MATIC,
                logoURI: 'https://etherscan.io/token/images/matictoken_28.png',
            },
            _b[ChainKey.POL] = {
                id: '0x0000000000000000000000000000000000000000',
                symbol: CoinKey.MATIC,
                decimals: 18,
                chainId: ChainId.POL,
                chainKey: ChainKey.POL,
                key: CoinKey.MATIC,
                name: CoinKey.MATIC,
                logoURI: 'https://etherscan.io/token/images/matictoken_28.png',
            },
            _b[ChainKey.DAI] = {
                id: '0x7122d7661c4564b7c6cd4878b06766489a6028a2',
                symbol: CoinKey.MATIC,
                decimals: 18,
                chainId: ChainId.DAI,
                chainKey: ChainKey.DAI,
                key: CoinKey.MATIC,
                name: CoinKey.MATIC,
                logoURI: 'https://etherscan.io/token/images/matictoken_28.png',
            },
            // Testnet
            _b[ChainKey.MUM] = {
                id: '0x0000000000000000000000000000000000000000',
                symbol: CoinKey.MATIC,
                decimals: 18,
                chainId: ChainId.MUM,
                chainKey: ChainKey.MUM,
                key: CoinKey.MATIC,
                name: CoinKey.MATIC,
                logoURI: 'https://etherscan.io/token/images/matictoken_28.png',
            },
            _b),
    },
    // > BNB
    {
        key: CoinKey.BNB,
        name: CoinKey.BNB,
        logoURI: 'https://assets.coingecko.com/coins/images/825/small/binance-coin-logo.png?1547034615',
        verified: true,
        chains: (_c = {},
            _c[ChainKey.ETH] = {
                id: '0xb8c77482e45f1f44de1745f52c74426c631bdd52',
                symbol: CoinKey.BNB,
                decimals: 18,
                chainId: ChainId.ETH,
                chainKey: ChainKey.ETH,
                key: CoinKey.BNB,
                name: CoinKey.BNB,
                logoURI: 'https://assets.coingecko.com/coins/images/825/small/binance-coin-logo.png?1547034615',
            },
            _c[ChainKey.BSC] = {
                id: '0x0000000000000000000000000000000000000000',
                symbol: CoinKey.BNB,
                decimals: 18,
                chainId: ChainId.BSC,
                chainKey: ChainKey.BSC,
                key: CoinKey.BNB,
                name: CoinKey.BNB,
                logoURI: 'https://assets.coingecko.com/coins/images/825/small/binance-coin-logo.png?1547034615',
            },
            _c[ChainKey.POL] = {
                id: '0xa649325aa7c5093d12d6f98eb4378deae68ce23f',
                symbol: CoinKey.BNB,
                decimals: 18,
                chainId: ChainId.POL,
                chainKey: ChainKey.POL,
                key: CoinKey.BNB,
                name: CoinKey.BNB,
                logoURI: 'https://assets.coingecko.com/coins/images/825/small/binance-coin-logo.png?1547034615',
            },
            _c[ChainKey.DAI] = {
                id: '0xca8d20f3e0144a72c6b5d576e9bd3fd8557e2b04',
                symbol: CoinKey.BNB,
                decimals: 18,
                chainId: ChainId.DAI,
                chainKey: ChainKey.DAI,
                key: CoinKey.BNB,
                name: CoinKey.BNB,
                logoURI: 'https://assets.coingecko.com/coins/images/825/small/binance-coin-logo.png?1547034615',
            },
            _c[ChainKey.ONE] = {
                id: '0xb1f6e61e1e113625593a22fa6aa94f8052bc39e0',
                symbol: CoinKey.BNB,
                decimals: 18,
                chainId: ChainId.ONE,
                chainKey: ChainKey.ONE,
                key: CoinKey.BNB,
                name: CoinKey.BNB,
                logoURI: 'https://assets.coingecko.com/coins/images/825/small/binance-coin-logo.png?1547034615',
            },
            // Testnet
            _c[ChainKey.BSCT] = {
                id: '0x0000000000000000000000000000000000000000',
                symbol: CoinKey.BNB,
                decimals: 18,
                chainId: ChainId.BSCT,
                chainKey: ChainKey.BSCT,
                key: CoinKey.BNB,
                name: CoinKey.BNB,
                logoURI: 'https://assets.coingecko.com/coins/images/825/small/binance-coin-logo.png?1547034615',
            },
            _c[ChainKey.ONET] = {
                id: '0xbef55684b382bae72051813a898d17282066c007',
                symbol: CoinKey.BNB,
                decimals: 18,
                chainId: ChainId.ONET,
                chainKey: ChainKey.ONET,
                key: CoinKey.BNB,
                name: CoinKey.BNB,
                logoURI: 'https://assets.coingecko.com/coins/images/825/small/binance-coin-logo.png?1547034615',
            },
            _c),
    },
    // > DAI
    {
        key: CoinKey.DAI,
        name: CoinKey.DAI,
        logoURI: 'https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0x6B175474E89094C44Da98b954EedeAC495271d0F/logo.png',
        verified: true,
        chains: (_d = {},
            _d[ChainKey.ETH] = {
                id: '0x6b175474e89094c44da98b954eedeac495271d0f',
                symbol: CoinKey.DAI,
                decimals: 18,
                chainId: ChainId.ETH,
                chainKey: ChainKey.ETH,
                key: CoinKey.DAI,
                name: CoinKey.DAI,
                logoURI: 'https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0x6B175474E89094C44Da98b954EedeAC495271d0F/logo.png',
            },
            _d[ChainKey.BSC] = {
                id: '0x1af3f329e8be154074d8769d1ffa4ee058b1dbc3',
                symbol: CoinKey.DAI,
                decimals: 18,
                chainId: ChainId.BSC,
                chainKey: ChainKey.BSC,
                key: CoinKey.DAI,
                name: CoinKey.DAI,
                logoURI: 'https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0x6B175474E89094C44Da98b954EedeAC495271d0F/logo.png',
            },
            _d[ChainKey.POL] = {
                id: '0x8f3cf7ad23cd3cadbd9735aff958023239c6a063',
                symbol: CoinKey.DAI,
                decimals: 18,
                chainId: ChainId.POL,
                chainKey: ChainKey.POL,
                key: CoinKey.DAI,
                name: CoinKey.DAI,
                logoURI: 'https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0x6B175474E89094C44Da98b954EedeAC495271d0F/logo.png',
            },
            _d[ChainKey.DAI] = {
                id: '0x0000000000000000000000000000000000000000',
                symbol: CoinKey.DAI,
                decimals: 18,
                chainId: ChainId.DAI,
                chainKey: ChainKey.DAI,
                key: CoinKey.DAI,
                name: CoinKey.DAI,
                logoURI: 'https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0x6B175474E89094C44Da98b954EedeAC495271d0F/logo.png',
            },
            _d[ChainKey.FTM] = {
                id: '0x8d11ec38a3eb5e956b052f67da8bdc9bef8abf3e',
                symbol: CoinKey.DAI,
                decimals: 18,
                chainId: ChainId.FTM,
                chainKey: ChainKey.FTM,
                key: CoinKey.DAI,
                name: CoinKey.DAI,
                logoURI: 'https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0x6B175474E89094C44Da98b954EedeAC495271d0F/logo.png',
            },
            _d[ChainKey.ONE] = {
                id: '0xEf977d2f931C1978Db5F6747666fa1eACB0d0339',
                symbol: CoinKey.DAI,
                decimals: 18,
                chainId: ChainId.ONE,
                chainKey: ChainKey.ONE,
                key: CoinKey.DAI,
                name: CoinKey.DAI,
                logoURI: 'https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0x6B175474E89094C44Da98b954EedeAC495271d0F/logo.png',
            },
            _d[ChainKey.AVA] = {
                id: '0xd586e7f844cea2f87f50152665bcbc2c279d8d70',
                symbol: CoinKey.DAI,
                decimals: 18,
                chainId: ChainId.AVA,
                chainKey: ChainKey.AVA,
                key: CoinKey.DAI,
                name: CoinKey.DAI,
                logoURI: 'https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0x6B175474E89094C44Da98b954EedeAC495271d0F/logo.png',
            },
            _d[ChainKey.ARB] = {
                id: '0xda10009cbd5d07dd0cecc66161fc93d7c9000da1',
                symbol: CoinKey.DAI,
                decimals: 18,
                chainId: ChainId.ARB,
                chainKey: ChainKey.ARB,
                key: CoinKey.DAI,
                name: CoinKey.DAI,
                logoURI: 'https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0x6B175474E89094C44Da98b954EedeAC495271d0F/logo.png',
            },
            // Testnets
            _d[ChainKey.ROP] = {
                id: '0x31f42841c2db5173425b5223809cf3a38fede360',
                symbol: CoinKey.DAI,
                decimals: 18,
                chainId: ChainId.ROP,
                chainKey: ChainKey.ROP,
                key: CoinKey.DAI,
                name: CoinKey.DAI,
                logoURI: 'https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0x6B175474E89094C44Da98b954EedeAC495271d0F/logo.png',
            },
            _d[ChainKey.RIN] = {
                id: '0x5592ec0cfb4dbc12d3ab100b257153436a1f0fea',
                symbol: CoinKey.DAI,
                decimals: 18,
                chainId: ChainId.RIN,
                chainKey: ChainKey.RIN,
                key: CoinKey.DAI,
                name: CoinKey.DAI,
                logoURI: 'https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0x6B175474E89094C44Da98b954EedeAC495271d0F/logo.png',
            },
            _d[ChainKey.GOR] = {
                id: '0xc61ba16e864efbd06a9fe30aab39d18b8f63710a',
                symbol: CoinKey.DAI,
                decimals: 18,
                chainId: ChainId.GOR,
                chainKey: ChainKey.GOR,
                key: CoinKey.DAI,
                name: CoinKey.DAI,
                logoURI: 'https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0x6B175474E89094C44Da98b954EedeAC495271d0F/logo.png',
            },
            _d[ChainKey.MUM] = {
                id: '0xb224913CE3851b0a0d7C0FB461eEF40f2e31ddb8',
                symbol: CoinKey.DAI,
                decimals: 18,
                chainId: ChainId.MUM,
                chainKey: ChainKey.MUM,
                key: CoinKey.DAI,
                name: CoinKey.DAI,
                logoURI: 'https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0x6B175474E89094C44Da98b954EedeAC495271d0F/logo.png',
            },
            _d),
    },
    // > FTM
    {
        key: CoinKey.FTM,
        name: CoinKey.FTM,
        logoURI: 'https://assets.spookyswap.finance/tokens/FTM.png',
        verified: true,
        chains: (_e = {},
            _e[ChainKey.FTM] = {
                id: '0x0000000000000000000000000000000000000000',
                symbol: CoinKey.FTM,
                decimals: 18,
                chainId: ChainId.FTM,
                chainKey: ChainKey.FTM,
                key: CoinKey.FTM,
                name: CoinKey.FTM,
                logoURI: 'https://assets.spookyswap.finance/tokens/FTM.png',
            },
            _e),
    },
    // > OKT
    {
        key: CoinKey.OKT,
        name: CoinKey.OKT,
        logoURI: '',
        verified: true,
        chains: (_f = {},
            _f[ChainKey.OKT] = {
                id: '0x0000000000000000000000000000000000000000',
                symbol: CoinKey.OKT,
                decimals: 18,
                chainId: ChainId.OKT,
                chainKey: ChainKey.OKT,
                key: CoinKey.OKT,
                name: CoinKey.OKT,
                logoURI: '',
            },
            _f),
    },
    // > AVAX
    {
        key: CoinKey.AVAX,
        name: CoinKey.AVAX,
        logoURI: '',
        verified: true,
        chains: (_g = {},
            _g[ChainKey.AVA] = {
                id: '0x0000000000000000000000000000000000000000',
                symbol: CoinKey.AVAX,
                decimals: 18,
                chainId: ChainId.AVA,
                chainKey: ChainKey.AVA,
                key: CoinKey.AVAX,
                name: CoinKey.AVAX,
                logoURI: '',
            },
            _g),
    },
    // > HT
    {
        key: CoinKey.HT,
        name: CoinKey.HT,
        logoURI: 'https://static.debank.com/image/heco_token/logo_url/heco/c399dcddde07e1944c4dd8f922832b53.png',
        verified: true,
        chains: (_h = {},
            _h[ChainKey.HEC] = {
                id: '0x0000000000000000000000000000000000000000',
                symbol: CoinKey.HT,
                decimals: 18,
                chainId: ChainId.HEC,
                chainKey: ChainKey.HEC,
                key: CoinKey.HT,
                name: CoinKey.HT,
                logoURI: 'https://static.debank.com/image/heco_token/logo_url/heco/c399dcddde07e1944c4dd8f922832b53.png',
            },
            _h),
    },
    // > ONE
    {
        key: CoinKey.ONE,
        name: CoinKey.ONE,
        logoURI: 'https://d1xrz6ki9z98vb.cloudfront.net/venomswap/tokens/WONE.png',
        verified: true,
        chains: (_j = {},
            _j[ChainKey.ONE] = {
                id: '0x0000000000000000000000000000000000000000',
                symbol: CoinKey.ONE,
                decimals: 18,
                chainId: ChainId.ONE,
                chainKey: ChainKey.ONE,
                key: CoinKey.ONE,
                name: CoinKey.ONE,
                logoURI: 'https://d1xrz6ki9z98vb.cloudfront.net/venomswap/tokens/WONE.png',
            },
            _j[ChainKey.BSC] = {
                id: '0x03ff0ff224f904be3118461335064bb48df47938',
                symbol: CoinKey.ONE,
                decimals: 18,
                chainId: ChainId.BSC,
                chainKey: ChainKey.BSC,
                key: CoinKey.ONE,
                name: CoinKey.ONE,
                logoURI: 'https://d1xrz6ki9z98vb.cloudfront.net/venomswap/tokens/WONE.png',
            },
            // Testnet
            _j[ChainKey.ONET] = {
                id: '0x0000000000000000000000000000000000000000',
                symbol: CoinKey.ONE,
                decimals: 18,
                chainId: ChainId.ONET,
                chainKey: ChainKey.ONET,
                key: CoinKey.ONE,
                name: CoinKey.ONE,
                logoURI: 'https://d1xrz6ki9z98vb.cloudfront.net/venomswap/tokens/WONE.png',
            },
            _j),
    },
    // OTHER STABLECOINS
    // USDT
    {
        key: CoinKey.USDT,
        name: CoinKey.USDT,
        logoURI: 'https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xdAC17F958D2ee523a2206206994597C13D831ec7/logo.png',
        verified: true,
        chains: (_k = {},
            _k[ChainKey.ETH] = {
                id: '0xdac17f958d2ee523a2206206994597c13d831ec7',
                symbol: CoinKey.USDT,
                decimals: 6,
                chainId: ChainId.ETH,
                chainKey: ChainKey.ETH,
                key: CoinKey.USDT,
                name: CoinKey.USDT,
                logoURI: 'https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xdAC17F958D2ee523a2206206994597C13D831ec7/logo.png',
            },
            _k[ChainKey.BSC] = {
                id: '0x55d398326f99059ff775485246999027b3197955',
                symbol: CoinKey.USDT,
                decimals: 18,
                chainId: ChainId.BSC,
                chainKey: ChainKey.BSC,
                key: CoinKey.USDT,
                name: CoinKey.USDT,
                logoURI: 'https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xdAC17F958D2ee523a2206206994597C13D831ec7/logo.png',
            },
            _k[ChainKey.POL] = {
                id: '0xc2132d05d31c914a87c6611c10748aeb04b58e8f',
                symbol: CoinKey.USDT,
                decimals: 6,
                chainId: ChainId.POL,
                chainKey: ChainKey.POL,
                key: CoinKey.USDT,
                name: CoinKey.USDT,
                logoURI: 'https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xdAC17F958D2ee523a2206206994597C13D831ec7/logo.png',
            },
            _k[ChainKey.DAI] = {
                id: '0x4ecaba5870353805a9f068101a40e0f32ed605c6',
                symbol: CoinKey.USDT,
                decimals: 6,
                chainId: ChainId.DAI,
                chainKey: ChainKey.DAI,
                key: CoinKey.USDT,
                name: CoinKey.USDT,
                logoURI: 'https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xdAC17F958D2ee523a2206206994597C13D831ec7/logo.png',
            },
            _k[ChainKey.FTM] = {
                id: '0x049d68029688eabf473097a2fc38ef61633a3c7a',
                symbol: CoinKey.USDT,
                decimals: 6,
                chainId: ChainId.FTM,
                chainKey: ChainKey.FTM,
                key: CoinKey.USDT,
                name: CoinKey.USDT,
                logoURI: 'https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xdAC17F958D2ee523a2206206994597C13D831ec7/logo.png',
            },
            _k[ChainKey.ARB] = {
                id: '0xfd086bc7cd5c481dcc9c85ebe478a1c0b69fcbb9',
                symbol: CoinKey.USDT,
                decimals: 6,
                chainId: ChainId.ARB,
                chainKey: ChainKey.ARB,
                key: CoinKey.USDT,
                name: CoinKey.USDT,
                logoURI: 'https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xdAC17F958D2ee523a2206206994597C13D831ec7/logo.png',
            },
            _k[ChainKey.OPT] = {
                id: '0x94b008aA00579c1307B0EF2c499aD98a8ce58e58',
                symbol: CoinKey.USDT,
                decimals: 6,
                chainId: ChainId.OPT,
                chainKey: ChainKey.OPT,
                key: CoinKey.USDT,
                name: CoinKey.USDT,
                logoURI: 'https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xdAC17F958D2ee523a2206206994597C13D831ec7/logo.png',
            },
            _k[ChainKey.ONE] = {
                id: '0x3c2b8be99c50593081eaa2a724f0b8285f5aba8f',
                symbol: CoinKey.USDT,
                decimals: 6,
                chainId: ChainId.ONE,
                chainKey: ChainKey.ONE,
                key: CoinKey.USDT,
                name: CoinKey.USDT,
                logoURI: 'https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xdAC17F958D2ee523a2206206994597C13D831ec7/logo.png',
            },
            _k[ChainKey.AVA] = {
                id: '0xc7198437980c041c805a1edcba50c1ce5db95118',
                symbol: CoinKey.USDT,
                decimals: 6,
                chainId: ChainId.AVA,
                chainKey: ChainKey.AVA,
                key: CoinKey.USDT,
                name: CoinKey.USDT,
                logoURI: 'https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xdAC17F958D2ee523a2206206994597C13D831ec7/logo.png',
            },
            // Testnets
            _k[ChainKey.ROP] = {
                id: '0x110a13fc3efe6a245b50102d2d79b3e76125ae83',
                symbol: CoinKey.USDT,
                decimals: 6,
                chainId: ChainId.ROP,
                chainKey: ChainKey.ROP,
                key: CoinKey.USDT,
                name: CoinKey.USDT,
                logoURI: 'https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xdAC17F958D2ee523a2206206994597C13D831ec7/logo.png',
            },
            _k[ChainKey.RIN] = {
                id: '0xd9ba894e0097f8cc2bbc9d24d308b98e36dc6d02',
                symbol: CoinKey.USDT,
                decimals: 6,
                chainId: ChainId.RIN,
                chainKey: ChainKey.RIN,
                key: CoinKey.USDT,
                name: CoinKey.USDT,
                logoURI: 'https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xdAC17F958D2ee523a2206206994597C13D831ec7/logo.png',
            },
            _k),
    },
    // USDC
    {
        key: CoinKey.USDC,
        name: CoinKey.USDC,
        logoURI: 'https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48/logo.png',
        verified: true,
        chains: (_l = {},
            _l[ChainKey.ETH] = {
                id: '0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48',
                symbol: CoinKey.USDC,
                decimals: 6,
                chainId: ChainId.ETH,
                chainKey: ChainKey.ETH,
                key: CoinKey.USDC,
                name: CoinKey.USDC,
                logoURI: 'https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48/logo.png',
            },
            _l[ChainKey.BSC] = {
                id: '0x8ac76a51cc950d9822d68b83fe1ad97b32cd580d',
                symbol: CoinKey.USDC,
                decimals: 18,
                chainId: ChainId.BSC,
                chainKey: ChainKey.BSC,
                key: CoinKey.USDC,
                name: CoinKey.USDC,
                logoURI: 'https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48/logo.png',
            },
            _l[ChainKey.POL] = {
                id: '0x2791bca1f2de4661ed88a30c99a7a9449aa84174',
                symbol: CoinKey.USDC,
                decimals: 6,
                chainId: ChainId.POL,
                chainKey: ChainKey.POL,
                key: CoinKey.USDC,
                name: CoinKey.USDC,
                logoURI: 'https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48/logo.png',
            },
            _l[ChainKey.DAI] = {
                id: '0xddafbb505ad214d7b80b1f830fccc89b60fb7a83',
                symbol: CoinKey.USDC,
                decimals: 6,
                chainId: ChainId.DAI,
                chainKey: ChainKey.DAI,
                key: CoinKey.USDC,
                name: CoinKey.USDC,
                logoURI: 'https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48/logo.png',
            },
            _l[ChainKey.FTM] = {
                id: '0x04068da6c83afcfa0e13ba15a6696662335d5b75',
                symbol: CoinKey.USDC,
                decimals: 6,
                chainId: 250,
                chainKey: ChainKey.FTM,
                key: CoinKey.USDC,
                name: CoinKey.USDC,
                logoURI: 'https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48/logo.png',
            },
            _l[ChainKey.ARB] = {
                id: '0xff970a61a04b1ca14834a43f5de4533ebddb5cc8',
                symbol: CoinKey.USDC,
                decimals: 6,
                chainId: ChainId.ARB,
                chainKey: ChainKey.ARB,
                key: CoinKey.USDC,
                name: CoinKey.USDC,
                logoURI: 'https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48/logo.png',
            },
            _l[ChainKey.OPT] = {
                id: '0x7F5c764cBc14f9669B88837ca1490cCa17c31607',
                symbol: CoinKey.USDC,
                decimals: 6,
                chainId: ChainId.OPT,
                chainKey: ChainKey.OPT,
                key: CoinKey.USDC,
                name: CoinKey.USDC,
                logoURI: 'https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48/logo.png',
            },
            _l[ChainKey.ONE] = {
                id: '0x985458e523db3d53125813ed68c274899e9dfab4',
                symbol: CoinKey.USDC,
                decimals: 6,
                chainId: ChainId.ONE,
                chainKey: ChainKey.ONE,
                key: CoinKey.USDC,
                name: CoinKey.USDC,
                logoURI: 'https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48/logo.png',
            },
            _l[ChainKey.AVA] = {
                id: '0xa7d7079b0fead91f3e65f86e8915cb59c1a4c664',
                symbol: CoinKey.USDC,
                decimals: 6,
                chainId: ChainId.AVA,
                chainKey: ChainKey.AVA,
                key: CoinKey.USDC,
                name: CoinKey.USDC,
                logoURI: 'https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48/logo.png',
            },
            // Testnets
            _l[ChainKey.ROP] = {
                id: '0x07865c6e87b9f70255377e024ace6630c1eaa37f',
                symbol: CoinKey.USDC,
                decimals: 6,
                chainId: ChainId.ROP,
                chainKey: ChainKey.ROP,
                key: CoinKey.USDC,
                name: CoinKey.USDC,
                logoURI: 'https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48/logo.png',
            },
            _l[ChainKey.RIN] = {
                id: '0x4dbcdf9b62e891a7cec5a2568c3f4faf9e8abe2b',
                symbol: CoinKey.USDC,
                decimals: 6,
                chainId: ChainId.RIN,
                chainKey: ChainKey.RIN,
                key: CoinKey.USDC,
                name: CoinKey.USDC,
                logoURI: 'https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48/logo.png',
            },
            _l[ChainKey.GOR] = {
                id: '0xd87ba7a50b2e7e660f678a895e4b72e7cb4ccd9c',
                symbol: CoinKey.USDC,
                decimals: 6,
                chainId: ChainId.GOR,
                chainKey: ChainKey.GOR,
                key: CoinKey.USDC,
                name: CoinKey.USDC,
                logoURI: 'https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48/logo.png',
            },
            _l[ChainKey.MUM] = {
                id: '0x6D4dd09982853F08d9966aC3cA4Eb5885F16f2b2',
                symbol: CoinKey.USDC,
                decimals: 6,
                chainId: ChainId.MUM,
                chainKey: ChainKey.MUM,
                key: CoinKey.USDC,
                name: CoinKey.USDC,
                logoURI: 'https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48/logo.png',
            },
            _l),
    },
    // TEST COIN
    {
        key: CoinKey.TEST,
        name: CoinKey.TEST,
        logoURI: 'https://xpollinate.io/icon192.png',
        verified: false,
        chains: (_m = {},
            _m[ChainKey.ROP] = {
                id: '0xe71678794fff8846bff855f716b0ce9d9a78e844',
                symbol: CoinKey.TEST,
                decimals: 18,
                chainId: ChainId.ROP,
                chainKey: ChainKey.ROP,
                key: CoinKey.TEST,
                name: CoinKey.TEST,
                logoURI: 'https://xpollinate.io/icon192.png',
            },
            _m[ChainKey.RIN] = {
                id: '0x9ac2c46d7acc21c881154d57c0dc1c55a3139198',
                symbol: CoinKey.TEST,
                decimals: 18,
                chainId: ChainId.RIN,
                chainKey: ChainKey.RIN,
                key: CoinKey.TEST,
                name: CoinKey.TEST,
                logoURI: 'https://xpollinate.io/icon192.png',
            },
            _m[ChainKey.GOR] = {
                id: '0x8a1cad3703e0beae0e0237369b4fcd04228d1682',
                symbol: CoinKey.TEST,
                decimals: 18,
                chainId: ChainId.GOR,
                chainKey: ChainKey.GOR,
                key: CoinKey.TEST,
                name: CoinKey.TEST,
                logoURI: 'https://xpollinate.io/icon192.png',
            },
            _m[ChainKey.MUM] = {
                id: '0xe71678794fff8846bff855f716b0ce9d9a78e844',
                symbol: CoinKey.TEST,
                decimals: 18,
                chainId: ChainId.MUM,
                chainKey: ChainKey.MUM,
                key: CoinKey.TEST,
                name: CoinKey.TEST,
                logoURI: 'https://xpollinate.io/icon192.png',
            },
            _m[ChainKey.ARBT] = {
                id: '0xe71678794fff8846bff855f716b0ce9d9a78e844',
                symbol: CoinKey.TEST,
                decimals: 18,
                chainId: ChainId.ARBT,
                chainKey: ChainKey.ARBT,
                key: CoinKey.TEST,
                name: CoinKey.TEST,
                logoURI: 'https://xpollinate.io/icon192.png',
            },
            _m[ChainKey.BSCT] = {
                id: '0xd86bcb7d85163fbc81756bb9cc22225d6abccadb',
                symbol: CoinKey.TEST,
                decimals: 18,
                chainId: ChainId.BSCT,
                chainKey: ChainKey.BSCT,
                key: CoinKey.TEST,
                name: CoinKey.TEST,
                logoURI: 'https://xpollinate.io/icon192.png',
            },
            _m[ChainKey.OPTT] = {
                id: '0xe71678794fff8846bff855f716b0ce9d9a78e844',
                symbol: CoinKey.TEST,
                decimals: 18,
                chainId: ChainId.OPTT,
                chainKey: ChainKey.OPTT,
                key: CoinKey.TEST,
                name: CoinKey.TEST,
                logoURI: 'https://xpollinate.io/icon192.png',
            },
            _m),
    },
];
export var findDefaultCoin = function (coinKey) {
    var coin = defaultCoins.find(function (coin) { return coin.key === coinKey; });
    if (!coin) {
        throw new Error('Invalid Coin');
    }
    return coin;
};
export var findDefaultCoinOnChain = function (coinKey, chainKey) {
    var coin = findDefaultCoin(coinKey);
    return coin.chains[chainKey];
};
export var defaultTokens = (_o = {},
    _o[ChainKey.ETH] = [
        findDefaultCoinOnChain(CoinKey.ETH, ChainKey.ETH),
        findDefaultCoinOnChain(CoinKey.USDC, ChainKey.ETH),
        findDefaultCoinOnChain(CoinKey.USDT, ChainKey.ETH),
        findDefaultCoinOnChain(CoinKey.MATIC, ChainKey.ETH),
    ],
    _o[ChainKey.BSC] = [
        findDefaultCoinOnChain(CoinKey.BNB, ChainKey.BSC),
        findDefaultCoinOnChain(CoinKey.USDC, ChainKey.BSC),
        findDefaultCoinOnChain(CoinKey.USDT, ChainKey.BSC),
        findDefaultCoinOnChain(CoinKey.DAI, ChainKey.BSC),
    ],
    _o[ChainKey.POL] = [
        findDefaultCoinOnChain(CoinKey.MATIC, ChainKey.POL),
        findDefaultCoinOnChain(CoinKey.USDC, ChainKey.POL),
        findDefaultCoinOnChain(CoinKey.USDT, ChainKey.POL),
        findDefaultCoinOnChain(CoinKey.DAI, ChainKey.POL),
    ],
    _o[ChainKey.DAI] = [
        findDefaultCoinOnChain(CoinKey.DAI, ChainKey.DAI),
        findDefaultCoinOnChain(CoinKey.USDC, ChainKey.DAI),
        findDefaultCoinOnChain(CoinKey.USDT, ChainKey.DAI),
        findDefaultCoinOnChain(CoinKey.MATIC, ChainKey.DAI),
    ],
    _o[ChainKey.FTM] = [
        findDefaultCoinOnChain(CoinKey.FTM, ChainKey.FTM),
        findDefaultCoinOnChain(CoinKey.USDC, ChainKey.FTM),
        findDefaultCoinOnChain(CoinKey.USDT, ChainKey.FTM),
        findDefaultCoinOnChain(CoinKey.DAI, ChainKey.FTM),
    ],
    _o[ChainKey.ARB] = [
        findDefaultCoinOnChain(CoinKey.USDC, ChainKey.ARB),
        findDefaultCoinOnChain(CoinKey.USDT, ChainKey.ARB),
        findDefaultCoinOnChain(CoinKey.DAI, ChainKey.ARB),
    ],
    _o[ChainKey.OPT] = [
        // findDefaultCoinOnChain(CoinKey.ETH, ChainKey.OPT),
        findDefaultCoinOnChain(CoinKey.USDC, ChainKey.OPT),
        findDefaultCoinOnChain(CoinKey.USDT, ChainKey.OPT),
    ],
    _o[ChainKey.ONE] = [
        findDefaultCoinOnChain(CoinKey.ONE, ChainKey.ONE),
        findDefaultCoinOnChain(CoinKey.BNB, ChainKey.ONE),
        findDefaultCoinOnChain(CoinKey.ETH, ChainKey.ONE),
    ],
    _o[ChainKey.AVA] = [
        findDefaultCoinOnChain(CoinKey.USDC, ChainKey.AVA),
        findDefaultCoinOnChain(CoinKey.USDT, ChainKey.AVA),
        findDefaultCoinOnChain(CoinKey.DAI, ChainKey.AVA),
    ],
    // Testnet
    _o[ChainKey.GOR] = [
        findDefaultCoinOnChain(CoinKey.ETH, ChainKey.GOR),
        findDefaultCoinOnChain(CoinKey.TEST, ChainKey.GOR),
        findDefaultCoinOnChain(CoinKey.USDC, ChainKey.GOR),
        // findDefaultCoinOnChain(CoinKey.USDT, ChainKey.GOR),
        findDefaultCoinOnChain(CoinKey.DAI, ChainKey.GOR),
    ],
    _o[ChainKey.RIN] = [
        findDefaultCoinOnChain(CoinKey.ETH, ChainKey.RIN),
        findDefaultCoinOnChain(CoinKey.TEST, ChainKey.RIN),
        findDefaultCoinOnChain(CoinKey.USDC, ChainKey.RIN),
        findDefaultCoinOnChain(CoinKey.USDT, ChainKey.RIN),
        findDefaultCoinOnChain(CoinKey.DAI, ChainKey.RIN),
    ],
    _o[ChainKey.ROP] = [
        findDefaultCoinOnChain(CoinKey.ETH, ChainKey.ROP),
        findDefaultCoinOnChain(CoinKey.TEST, ChainKey.ROP),
        findDefaultCoinOnChain(CoinKey.USDC, ChainKey.ROP),
        findDefaultCoinOnChain(CoinKey.USDT, ChainKey.ROP),
        findDefaultCoinOnChain(CoinKey.DAI, ChainKey.ROP),
    ],
    _o[ChainKey.KOV] = [findDefaultCoinOnChain(CoinKey.ETH, ChainKey.KOV)],
    _o[ChainKey.MUM] = [
        findDefaultCoinOnChain(CoinKey.MATIC, ChainKey.MUM),
        findDefaultCoinOnChain(CoinKey.TEST, ChainKey.MUM),
        findDefaultCoinOnChain(CoinKey.USDC, ChainKey.MUM),
        // findDefaultCoinOnChain(CoinKey.USDT, ChainKey.MUM),
        findDefaultCoinOnChain(CoinKey.DAI, ChainKey.MUM),
    ],
    _o[ChainKey.BSCT] = [findDefaultCoinOnChain(CoinKey.BNB, ChainKey.BSCT)],
    _o[ChainKey.ONET] = [
        findDefaultCoinOnChain(CoinKey.ONE, ChainKey.ONET),
        findDefaultCoinOnChain(CoinKey.ETH, ChainKey.ONET),
        findDefaultCoinOnChain(CoinKey.BNB, ChainKey.ONET),
    ],
    _o);
export var wrappedTokens = (_p = {},
    _p[ChainKey.ETH] = {
        // https://ww7.etherscan.io/token/0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2
        id: '0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2',
        symbol: 'WETH',
        decimals: 18,
        chainId: ChainId.ETH,
        chainKey: ChainKey.ETH,
        key: 'WETH',
        name: 'WETH',
        logoURI: 'https://zapper.fi/images/networks/ethereum/0x0000000000000000000000000000000000000000.png',
    },
    _p[ChainKey.BSC] = {
        // https://bscscan.com/token/0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c
        id: '0xbb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c',
        symbol: 'WBNB',
        decimals: 18,
        chainId: ChainId.BSC,
        chainKey: ChainKey.BSC,
        key: 'WBNB',
        name: 'WBNB',
        logoURI: 'https://zapper.fi/images/networks/binance-smart-chain/0x0000000000000000000000000000000000000000.png',
    },
    _p[ChainKey.POL] = {
        // https://polygonscan.com/token/0x0d500b1d8e8ef31e21c99d1db9a6444d3adf1270
        id: '0x0d500b1d8e8ef31e21c99d1db9a6444d3adf1270',
        symbol: 'WMATIC',
        decimals: 18,
        chainId: ChainId.POL,
        chainKey: ChainKey.POL,
        key: 'WMATIC',
        name: 'WMATIC',
        logoURI: 'https://zapper.fi/images/networks/polygon/0x0000000000000000000000000000000000000000.png',
    },
    _p[ChainKey.DAI] = {
        // https://blockscout.com/xdai/mainnet/address/0xe91D153E0b41518A2Ce8Dd3D7944Fa863463a97d
        id: '0xe91d153e0b41518a2ce8dd3d7944fa863463a97d',
        symbol: 'WXDAI',
        decimals: 18,
        chainId: ChainId.DAI,
        chainKey: ChainKey.DAI,
        key: 'WXDAI',
        name: 'WXDAI',
        logoURI: 'https://zapper.fi/images/networks/ethereum/0x6b175474e89094c44da98b954eedeac495271d0f.png',
    },
    _p[ChainKey.FTM] = {
        //
        id: '0x21be370D5312f44cB42ce377BC9b8a0cEF1A4C83',
        symbol: 'wFTM',
        decimals: 18,
        chainId: ChainId.FTM,
        chainKey: ChainKey.FTM,
        key: 'wFTM',
        name: 'wFTM',
        logoURI: 'https://assets.spookyswap.finance/coins/0x21be370D5312f44cB42ce377BC9b8a0cEF1A4C83.png',
    },
    _p[ChainKey.ONE] = {
        id: '0xcF664087a5bB0237a0BAd6742852ec6c8d69A27a',
        symbol: 'WONE',
        decimals: 18,
        chainId: ChainId.ONE,
        chainKey: ChainKey.ONE,
        key: 'WONE',
        name: 'WRAPPED ONE',
        logoURI: 'https://d1xrz6ki9z98vb.cloudfront.net/venomswap/tokens/WONE.png',
    },
    // Testnets
    _p[ChainKey.ROP] = {
        // https://ropsten.etherscan.io/token/0xc778417e063141139fce010982780140aa0cd5ab
        id: '0xc778417e063141139fce010982780140aa0cd5ab',
        symbol: 'WETH',
        decimals: 18,
        chainId: ChainId.ROP,
        chainKey: ChainKey.ROP,
        key: 'WETH',
        name: 'WETH',
        logoURI: 'https://zapper.fi/images/networks/ethereum/0x0000000000000000000000000000000000000000.png',
    },
    _p[ChainKey.RIN] = {
        // https://rinkeby.etherscan.io/token/0xc778417e063141139fce010982780140aa0cd5ab
        id: '0xc778417e063141139fce010982780140aa0cd5ab',
        symbol: 'WETH',
        decimals: 18,
        chainId: ChainId.RIN,
        chainKey: ChainKey.RIN,
        key: 'WETH',
        name: 'WETH',
        logoURI: 'https://zapper.fi/images/networks/ethereum/0x0000000000000000000000000000000000000000.png',
    },
    _p[ChainKey.GOR] = {
        // https://goerli.etherscan.io/token/0xb4fbf271143f4fbf7b91a5ded31805e42b2208d6
        id: '0xb4fbf271143f4fbf7b91a5ded31805e42b2208d6',
        symbol: 'WETH',
        decimals: 18,
        chainId: ChainId.GOR,
        chainKey: ChainKey.GOR,
        key: 'WETH',
        name: 'WETH',
        logoURI: 'https://zapper.fi/images/networks/ethereum/0x0000000000000000000000000000000000000000.png',
    },
    _p[ChainKey.MUM] = {
        // https://mumbai.polygonscan.com/token/0x9c3c9283d3e44854697cd22d3faa240cfb032889
        id: '0x9c3c9283d3e44854697cd22d3faa240cfb032889',
        symbol: 'WMATIC',
        decimals: 18,
        chainId: ChainId.MUM,
        chainKey: ChainKey.MUM,
        key: 'WMATIC',
        name: 'WMATIC',
        logoURI: 'https://zapper.fi/images/networks/polygon/0x0000000000000000000000000000000000000000.png',
    },
    _p[ChainKey.ONET] = {
        id: '0x7466d7d0C21Fa05F32F5a0Fa27e12bdC06348Ce2',
        symbol: 'WONE',
        decimals: 18,
        chainId: ChainId.ONET,
        chainKey: ChainKey.ONET,
        key: 'WONE',
        name: 'WRAPPED ONE',
        logoURI: 'https://d1xrz6ki9z98vb.cloudfront.net/venomswap/tokens/WONE.png',
    },
    _p);
// adapted from https://github.com/1Hive/honeyswap-interface/blob/b25a3cbdec5f43613b1b282ef620f8fad891c82f/src/constants/index.ts
// https://github.com/pancakeswap/pancake-frontend/blob/a3ff0beeb57a39d7de6c4d7fa0de0e639921eb0c/src/config/constants/index.ts
// https://github.com/Uniswap/uniswap-interface/blob/b14da2844d3d0ff7d9b6a099499b9402db52629c/src/constants/routing.ts
//
export var BASES_TO_CHECK_TRADES_AGAINST = (_q = {},
    _q[ChainKey.ETH] = [
        wrappedTokens[ChainKey.ETH],
        findDefaultCoinOnChain(CoinKey.DAI, ChainKey.ETH),
        findDefaultCoinOnChain(CoinKey.USDC, ChainKey.ETH),
        {
            id: '0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599',
            symbol: 'WBTC',
            decimals: 18,
            chainId: ChainId.DAI,
            chainKey: ChainKey.DAI,
        },
        findDefaultCoinOnChain(CoinKey.USDT, ChainKey.ETH),
    ],
    _q[ChainKey.DAI] = [
        wrappedTokens[ChainKey.DAI],
        findDefaultCoinOnChain(CoinKey.USDC, ChainKey.DAI),
        findDefaultCoinOnChain(CoinKey.USDT, ChainKey.DAI),
        {
            id: '0x8e5bBbb09Ed1ebdE8674Cda39A0c169401db4252',
            symbol: 'WBTC',
            decimals: 18,
            chainId: ChainId.DAI,
            chainKey: ChainKey.DAI,
        },
        {
            id: '0x71850b7e9ee3f13ab46d67167341e4bdc905eef9',
            symbol: 'HNY',
            decimals: 18,
            chainId: ChainId.DAI,
            chainKey: ChainKey.DAI,
        },
        {
            id: '0xb7D311E2Eb55F2f68a9440da38e7989210b9A05e',
            symbol: 'STAKE',
            decimals: 18,
            chainId: ChainId.DAI,
            chainKey: ChainKey.DAI,
        },
        {
            id: '0x3a97704a1b25F08aa230ae53B352e2e72ef52843',
            symbol: 'AGVE',
            decimals: 18,
            chainId: ChainId.DAI,
            chainKey: ChainKey.DAI,
        },
        {
            id: '0x82dFe19164729949fD66Da1a37BC70dD6c4746ce',
            symbol: 'BAO',
            decimals: 18,
            chainId: ChainId.DAI,
            chainKey: ChainKey.DAI,
        },
    ],
    _q[ChainKey.POL] = [
        // WETH[ChainId.MATIC],
        wrappedTokens[ChainKey.POL],
        {
            id: '0xb371248dd0f9e4061ccf8850e9223ca48aa7ca4b',
            symbol: 'HNY',
            decimals: 18,
            chainId: ChainId.POL,
            chainKey: ChainKey.POL,
        },
        findDefaultCoinOnChain(CoinKey.DAI, ChainKey.POL),
        findDefaultCoinOnChain(CoinKey.USDC, ChainKey.POL),
        findDefaultCoinOnChain(CoinKey.USDT, ChainKey.POL),
    ],
    _q[ChainKey.BSC] = [
        wrappedTokens[ChainKey.BSC],
        findDefaultCoinOnChain(CoinKey.DAI, ChainKey.BSC),
        findDefaultCoinOnChain(CoinKey.USDC, ChainKey.BSC),
        findDefaultCoinOnChain(CoinKey.USDT, ChainKey.BSC),
        {
            id: '0x0E09FaBB73Bd3Ade0a17ECC321fD13a19e81cE82',
            symbol: 'CAKE',
            decimals: 18,
            chainId: ChainId.BSC,
            chainKey: ChainKey.BSC,
        },
        {
            id: '0x7130d2A12B9BCbFAe4f2634d864A1Ee1Ce3Ead9c',
            symbol: 'BTCB',
            decimals: 18,
            chainId: ChainId.BSC,
            chainKey: ChainKey.BSC,
        },
        {
            id: '0x2170Ed0880ac9A755fd29B2688956BD959F933F8',
            symbol: 'ETH',
            decimals: 18,
            chainId: ChainId.BSC,
            chainKey: ChainKey.BSC,
        },
        {
            id: '0x23396cf899ca06c4472205fc903bdb4de249d6fc',
            symbol: 'ETH',
            decimals: 18,
            chainId: ChainId.BSC,
            chainKey: ChainKey.BSC,
        },
    ],
    _q[ChainKey.OKT] = [],
    _q[ChainKey.FTM] = [
        findDefaultCoinOnChain(CoinKey.FTM, ChainKey.FTM),
        findDefaultCoinOnChain(CoinKey.USDC, ChainKey.FTM),
        findDefaultCoinOnChain(CoinKey.USDT, ChainKey.FTM),
        findDefaultCoinOnChain(CoinKey.DAI, ChainKey.FTM),
    ],
    _q[ChainKey.AVA] = [],
    _q[ChainKey.ARB] = [],
    _q[ChainKey.HEC] = [],
    _q[ChainKey.OPT] = [],
    _q[ChainKey.ONE] = [
        wrappedTokens[ChainKey.ONE],
        findDefaultCoinOnChain(CoinKey.ETH, ChainKey.ONE),
        findDefaultCoinOnChain(CoinKey.DAI, ChainKey.ONE),
        findDefaultCoinOnChain(CoinKey.USDT, ChainKey.ONE),
        findDefaultCoinOnChain(CoinKey.USDC, ChainKey.ONE),
    ],
    // Testnets
    _q[ChainKey.ROP] = [wrappedTokens[ChainKey.ROP]],
    _q[ChainKey.RIN] = [wrappedTokens[ChainKey.RIN]],
    _q[ChainKey.GOR] = [wrappedTokens[ChainKey.GOR]],
    _q[ChainKey.KOV] = [],
    _q[ChainKey.MUM] = [wrappedTokens[ChainKey.MUM]],
    _q[ChainKey.ARBT] = [],
    _q[ChainKey.OPTT] = [],
    _q[ChainKey.BSCT] = [],
    _q[ChainKey.HECT] = [],
    _q[ChainKey.ONET] = [wrappedTokens[ChainKey.ONET]],
    _q);
